- name: Create Jenkins Jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
    mjobs:
      - { jobs_name: "cart", repo_name: "https://github.com/Abhimanyu9555657/cart" }
    sjobs:
      - { jobs_name: "roboshop-terraform", repo_name: "https://github.com/Abhimanyu9555657/roboshop-terraform" }


